/*
 * Whisper API Platform
 *
 * Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@whisper.security
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Noctis.FrontGraph.Sdk.Model;
using Noctis.FrontGraph.Sdk.Client;
using System.Reflection;

namespace Noctis.FrontGraph.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DomainIntelligenceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainIntelligenceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainIntelligenceResponse
        //private DomainIntelligenceResponse instance;

        public DomainIntelligenceResponseTests()
        {
            // TODO uncomment below to create an instance of DomainIntelligenceResponse
            //instance = new DomainIntelligenceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainIntelligenceResponse
        /// </summary>
        [Fact]
        public void DomainIntelligenceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainIntelligenceResponse
            //Assert.IsType<DomainIntelligenceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Registration'
        /// </summary>
        [Fact]
        public void RegistrationTest()
        {
            // TODO unit test for the property 'Registration'
        }

        /// <summary>
        /// Test the property 'Dns'
        /// </summary>
        [Fact]
        public void DnsTest()
        {
            // TODO unit test for the property 'Dns'
        }

        /// <summary>
        /// Test the property 'Relationships'
        /// </summary>
        [Fact]
        public void RelationshipsTest()
        {
            // TODO unit test for the property 'Relationships'
        }

        /// <summary>
        /// Test the property 'Trademark'
        /// </summary>
        [Fact]
        public void TrademarkTest()
        {
            // TODO unit test for the property 'Trademark'
        }

        /// <summary>
        /// Test the property 'IpIntelligence'
        /// </summary>
        [Fact]
        public void IpIntelligenceTest()
        {
            // TODO unit test for the property 'IpIntelligence'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
