/*
 * Whisper API Platform
 *
 * Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@whisper.security
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Noctis.FrontGraph.Sdk.Model;
using Noctis.FrontGraph.Sdk.Client;
using System.Reflection;

namespace Noctis.FrontGraph.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing IpIntelligenceResponseGeolocationCoordinates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IpIntelligenceResponseGeolocationCoordinatesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IpIntelligenceResponseGeolocationCoordinates
        //private IpIntelligenceResponseGeolocationCoordinates instance;

        public IpIntelligenceResponseGeolocationCoordinatesTests()
        {
            // TODO uncomment below to create an instance of IpIntelligenceResponseGeolocationCoordinates
            //instance = new IpIntelligenceResponseGeolocationCoordinates();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IpIntelligenceResponseGeolocationCoordinates
        /// </summary>
        [Fact]
        public void IpIntelligenceResponseGeolocationCoordinatesInstanceTest()
        {
            // TODO uncomment below to test "IsType" IpIntelligenceResponseGeolocationCoordinates
            //Assert.IsType<IpIntelligenceResponseGeolocationCoordinates>(instance);
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'AccuracyRadius'
        /// </summary>
        [Fact]
        public void AccuracyRadiusTest()
        {
            // TODO unit test for the property 'AccuracyRadius'
        }

        /// <summary>
        /// Test the property 'VarTimeZone'
        /// </summary>
        [Fact]
        public void VarTimeZoneTest()
        {
            // TODO unit test for the property 'VarTimeZone'
        }
    }
}
