/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AttributeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttributeRequest
        //private AttributeRequest instance;

        public AttributeRequestTests()
        {
            // TODO uncomment below to create an instance of AttributeRequest
            //instance = new AttributeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttributeRequest
        /// </summary>
        [Fact]
        public void AttributeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AttributeRequest
            //Assert.IsType<AttributeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Indicators'
        /// </summary>
        [Fact]
        public void IndicatorsTest()
        {
            // TODO unit test for the property 'Indicators'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
    }
}
