/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BulkRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkRequest
        //private BulkRequest instance;

        public BulkRequestTests()
        {
            // TODO uncomment below to create an instance of BulkRequest
            //instance = new BulkRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkRequest
        /// </summary>
        [Fact]
        public void BulkRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkRequest
            //Assert.IsType<BulkRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Indicators'
        /// </summary>
        [Fact]
        public void IndicatorsTest()
        {
            // TODO unit test for the property 'Indicators'
        }

        /// <summary>
        /// Test the property 'Include'
        /// </summary>
        [Fact]
        public void IncludeTest()
        {
            // TODO unit test for the property 'Include'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
    }
}
