/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinksInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinksInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinksInfo
        //private LinksInfo instance;

        public LinksInfoTests()
        {
            // TODO uncomment below to create an instance of LinksInfo
            //instance = new LinksInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinksInfo
        /// </summary>
        [Fact]
        public void LinksInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinksInfo
            //Assert.IsType<LinksInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'TopSources'
        /// </summary>
        [Fact]
        public void TopSourcesTest()
        {
            // TODO unit test for the property 'TopSources'
        }

        /// <summary>
        /// Test the property 'TopDestinations'
        /// </summary>
        [Fact]
        public void TopDestinationsTest()
        {
            // TODO unit test for the property 'TopDestinations'
        }
    }
}
