/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PivotRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PivotRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PivotRequest
        //private PivotRequest instance;

        public PivotRequestTests()
        {
            // TODO uncomment below to create an instance of PivotRequest
            //instance = new PivotRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PivotRequest
        /// </summary>
        [Fact]
        public void PivotRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PivotRequest
            //Assert.IsType<PivotRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Indicator'
        /// </summary>
        [Fact]
        public void IndicatorTest()
        {
            // TODO unit test for the property 'Indicator'
        }

        /// <summary>
        /// Test the property 'IndicatorType'
        /// </summary>
        [Fact]
        public void IndicatorTypeTest()
        {
            // TODO unit test for the property 'IndicatorType'
        }

        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Fact]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }

        /// <summary>
        /// Test the property 'Strategies'
        /// </summary>
        [Fact]
        public void StrategiesTest()
        {
            // TODO unit test for the property 'Strategies'
        }

        /// <summary>
        /// Test the property 'MaxNodes'
        /// </summary>
        [Fact]
        public void MaxNodesTest()
        {
            // TODO unit test for the property 'MaxNodes'
        }
    }
}
