/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PredictionPoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PredictionPointTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PredictionPoint
        //private PredictionPoint instance;

        public PredictionPointTests()
        {
            // TODO uncomment below to create an instance of PredictionPoint
            //instance = new PredictionPoint();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PredictionPoint
        /// </summary>
        [Fact]
        public void PredictionPointInstanceTest()
        {
            // TODO uncomment below to test "IsType" PredictionPoint
            //Assert.IsType<PredictionPoint>(instance);
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }

        /// <summary>
        /// Test the property 'PredictedScore'
        /// </summary>
        [Fact]
        public void PredictedScoreTest()
        {
            // TODO unit test for the property 'PredictedScore'
        }

        /// <summary>
        /// Test the property 'PredictedLevel'
        /// </summary>
        [Fact]
        public void PredictedLevelTest()
        {
            // TODO unit test for the property 'PredictedLevel'
        }
    }
}
