/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SimilarDomainsOpsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimilarDomainsOpsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimilarDomainsOpsRequest
        //private SimilarDomainsOpsRequest instance;

        public SimilarDomainsOpsRequestTests()
        {
            // TODO uncomment below to create an instance of SimilarDomainsOpsRequest
            //instance = new SimilarDomainsOpsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimilarDomainsOpsRequest
        /// </summary>
        [Fact]
        public void SimilarDomainsOpsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimilarDomainsOpsRequest
            //Assert.IsType<SimilarDomainsOpsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
    }
}
