/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Whisper.Api.Sdk.Model;
using Whisper.Api.Sdk.Client;
using System.Reflection;

namespace Whisper.Api.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TldVariationConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TldVariationConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TldVariationConfig
        //private TldVariationConfig instance;

        public TldVariationConfigTests()
        {
            // TODO uncomment below to create an instance of TldVariationConfig
            //instance = new TldVariationConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TldVariationConfig
        /// </summary>
        [Fact]
        public void TldVariationConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" TldVariationConfig
            //Assert.IsType<TldVariationConfig>(instance);
        }

        /// <summary>
        /// Test the property 'CommonTlds'
        /// </summary>
        [Fact]
        public void CommonTldsTest()
        {
            // TODO unit test for the property 'CommonTlds'
        }

        /// <summary>
        /// Test the property 'CountryTlds'
        /// </summary>
        [Fact]
        public void CountryTldsTest()
        {
            // TODO unit test for the property 'CountryTlds'
        }

        /// <summary>
        /// Test the property 'NewGtlds'
        /// </summary>
        [Fact]
        public void NewGtldsTest()
        {
            // TODO unit test for the property 'NewGtlds'
        }

        /// <summary>
        /// Test the property 'CustomTlds'
        /// </summary>
        [Fact]
        public void CustomTldsTest()
        {
            // TODO unit test for the property 'CustomTlds'
        }
    }
}
