// <auto-generated>
/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisper.Api.Sdk.Client;

namespace Whisper.Api.Sdk.Model
{
    /// <summary>
    /// Current risk state
    /// </summary>
    public partial class CurrentAssessment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentAssessment" /> class.
        /// </summary>
        /// <param name="confidence">Confidence in assessment (0-1)</param>
        /// <param name="riskScore">Current risk score (0-100)</param>
        /// <param name="riskLevel">Risk level category</param>
        /// <param name="assessedAt">Assessment timestamp</param>
        [JsonConstructor]
        public CurrentAssessment(Option<double?> confidence = default, Option<double?> riskScore = default, Option<string> riskLevel = default, Option<string> assessedAt = default)
        {
            ConfidenceOption = confidence;
            RiskScoreOption = riskScore;
            RiskLevelOption = riskLevel;
            AssessedAtOption = assessedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Confidence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ConfidenceOption { get; private set; }

        /// <summary>
        /// Confidence in assessment (0-1)
        /// </summary>
        /// <value>Confidence in assessment (0-1)</value>
        /* <example>0.89</example> */
        [JsonPropertyName("confidence")]
        public double? Confidence { get { return this.ConfidenceOption; } set { this.ConfidenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of RiskScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RiskScoreOption { get; private set; }

        /// <summary>
        /// Current risk score (0-100)
        /// </summary>
        /// <value>Current risk score (0-100)</value>
        /* <example>42.5</example> */
        [JsonPropertyName("riskScore")]
        public double? RiskScore { get { return this.RiskScoreOption; } set { this.RiskScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of RiskLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RiskLevelOption { get; private set; }

        /// <summary>
        /// Risk level category
        /// </summary>
        /// <value>Risk level category</value>
        /* <example>medium_risk</example> */
        [JsonPropertyName("riskLevel")]
        public string RiskLevel { get { return this.RiskLevelOption; } set { this.RiskLevelOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AssessedAtOption { get; private set; }

        /// <summary>
        /// Assessment timestamp
        /// </summary>
        /// <value>Assessment timestamp</value>
        [JsonPropertyName("assessedAt")]
        public string AssessedAt { get { return this.AssessedAtOption; } set { this.AssessedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CurrentAssessment {\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  RiskScore: ").Append(RiskScore).Append("\n");
            sb.Append("  RiskLevel: ").Append(RiskLevel).Append("\n");
            sb.Append("  AssessedAt: ").Append(AssessedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CurrentAssessment" />
    /// </summary>
    public class CurrentAssessmentJsonConverter : JsonConverter<CurrentAssessment>
    {
        /// <summary>
        /// Deserializes json to <see cref="CurrentAssessment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CurrentAssessment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> confidence = default;
            Option<double?> riskScore = default;
            Option<string> riskLevel = default;
            Option<string> assessedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "confidence":
                            confidence = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "riskScore":
                            riskScore = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "riskLevel":
                            riskLevel = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "assessedAt":
                            assessedAt = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (confidence.IsSet && confidence.Value == null)
                throw new ArgumentNullException(nameof(confidence), "Property is not nullable for class CurrentAssessment.");

            if (riskScore.IsSet && riskScore.Value == null)
                throw new ArgumentNullException(nameof(riskScore), "Property is not nullable for class CurrentAssessment.");

            if (riskLevel.IsSet && riskLevel.Value == null)
                throw new ArgumentNullException(nameof(riskLevel), "Property is not nullable for class CurrentAssessment.");

            if (assessedAt.IsSet && assessedAt.Value == null)
                throw new ArgumentNullException(nameof(assessedAt), "Property is not nullable for class CurrentAssessment.");

            return new CurrentAssessment(confidence, riskScore, riskLevel, assessedAt);
        }

        /// <summary>
        /// Serializes a <see cref="CurrentAssessment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="currentAssessment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CurrentAssessment currentAssessment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, currentAssessment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CurrentAssessment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="currentAssessment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CurrentAssessment currentAssessment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (currentAssessment.RiskLevelOption.IsSet && currentAssessment.RiskLevel == null)
                throw new ArgumentNullException(nameof(currentAssessment.RiskLevel), "Property is required for class CurrentAssessment.");

            if (currentAssessment.AssessedAtOption.IsSet && currentAssessment.AssessedAt == null)
                throw new ArgumentNullException(nameof(currentAssessment.AssessedAt), "Property is required for class CurrentAssessment.");

            if (currentAssessment.ConfidenceOption.IsSet)
                writer.WriteNumber("confidence", currentAssessment.ConfidenceOption.Value.Value);

            if (currentAssessment.RiskScoreOption.IsSet)
                writer.WriteNumber("riskScore", currentAssessment.RiskScoreOption.Value.Value);

            if (currentAssessment.RiskLevelOption.IsSet)
                writer.WriteString("riskLevel", currentAssessment.RiskLevel);

            if (currentAssessment.AssessedAtOption.IsSet)
                writer.WriteString("assessedAt", currentAssessment.AssessedAt);
        }
    }
}
