// <auto-generated>
/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisper.Api.Sdk.Client;

namespace Whisper.Api.Sdk.Model
{
    /// <summary>
    /// Request for intelligent infrastructure pivoting and relationship discovery
    /// </summary>
    public partial class PivotRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PivotRequest" /> class.
        /// </summary>
        /// <param name="indicator">Starting indicator for pivot analysis</param>
        /// <param name="indicatorType">Type of starting indicator</param>
        /// <param name="depth">Pivot depth (1-3)</param>
        /// <param name="strategies">Pivot strategies to use</param>
        /// <param name="maxNodes">Maximum nodes to discover</param>
        [JsonConstructor]
        public PivotRequest(string indicator, string indicatorType, Option<int?> depth = default, Option<List<string>> strategies = default, Option<int?> maxNodes = default)
        {
            Indicator = indicator;
            IndicatorType = indicatorType;
            DepthOption = depth;
            StrategiesOption = strategies;
            MaxNodesOption = maxNodes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Starting indicator for pivot analysis
        /// </summary>
        /// <value>Starting indicator for pivot analysis</value>
        /* <example>evil.com</example> */
        [JsonPropertyName("indicator")]
        public string Indicator { get; set; }

        /// <summary>
        /// Type of starting indicator
        /// </summary>
        /// <value>Type of starting indicator</value>
        /* <example>domain</example> */
        [JsonPropertyName("indicatorType")]
        public string IndicatorType { get; set; }

        /// <summary>
        /// Used to track the state of Depth
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DepthOption { get; private set; }

        /// <summary>
        /// Pivot depth (1-3)
        /// </summary>
        /// <value>Pivot depth (1-3)</value>
        /* <example>2</example> */
        [JsonPropertyName("depth")]
        public int? Depth { get { return this.DepthOption; } set { this.DepthOption = new(value); } }

        /// <summary>
        /// Used to track the state of Strategies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> StrategiesOption { get; private set; }

        /// <summary>
        /// Pivot strategies to use
        /// </summary>
        /// <value>Pivot strategies to use</value>
        [JsonPropertyName("strategies")]
        public List<string> Strategies { get { return this.StrategiesOption; } set { this.StrategiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaxNodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MaxNodesOption { get; private set; }

        /// <summary>
        /// Maximum nodes to discover
        /// </summary>
        /// <value>Maximum nodes to discover</value>
        /* <example>100</example> */
        [JsonPropertyName("maxNodes")]
        public int? MaxNodes { get { return this.MaxNodesOption; } set { this.MaxNodesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PivotRequest {\n");
            sb.Append("  Indicator: ").Append(Indicator).Append("\n");
            sb.Append("  IndicatorType: ").Append(IndicatorType).Append("\n");
            sb.Append("  Depth: ").Append(Depth).Append("\n");
            sb.Append("  Strategies: ").Append(Strategies).Append("\n");
            sb.Append("  MaxNodes: ").Append(MaxNodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Depth (int) maximum
            if (this.DepthOption.IsSet && this.DepthOption.Value > (int)3)
            {
                yield return new ValidationResult("Invalid value for Depth, must be a value less than or equal to 3.", new [] { "Depth" });
            }

            // Depth (int) minimum
            if (this.DepthOption.IsSet && this.DepthOption.Value < (int)1)
            {
                yield return new ValidationResult("Invalid value for Depth, must be a value greater than or equal to 1.", new [] { "Depth" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PivotRequest" />
    /// </summary>
    public class PivotRequestJsonConverter : JsonConverter<PivotRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="PivotRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PivotRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> indicator = default;
            Option<string> indicatorType = default;
            Option<int?> depth = default;
            Option<List<string>> strategies = default;
            Option<int?> maxNodes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "indicator":
                            indicator = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "indicatorType":
                            indicatorType = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "depth":
                            depth = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "strategies":
                            strategies = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "maxNodes":
                            maxNodes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!indicator.IsSet)
                throw new ArgumentException("Property is required for class PivotRequest.", nameof(indicator));

            if (!indicatorType.IsSet)
                throw new ArgumentException("Property is required for class PivotRequest.", nameof(indicatorType));

            if (indicator.IsSet && indicator.Value == null)
                throw new ArgumentNullException(nameof(indicator), "Property is not nullable for class PivotRequest.");

            if (indicatorType.IsSet && indicatorType.Value == null)
                throw new ArgumentNullException(nameof(indicatorType), "Property is not nullable for class PivotRequest.");

            if (depth.IsSet && depth.Value == null)
                throw new ArgumentNullException(nameof(depth), "Property is not nullable for class PivotRequest.");

            if (strategies.IsSet && strategies.Value == null)
                throw new ArgumentNullException(nameof(strategies), "Property is not nullable for class PivotRequest.");

            if (maxNodes.IsSet && maxNodes.Value == null)
                throw new ArgumentNullException(nameof(maxNodes), "Property is not nullable for class PivotRequest.");

            return new PivotRequest(indicator.Value, indicatorType.Value, depth, strategies, maxNodes);
        }

        /// <summary>
        /// Serializes a <see cref="PivotRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pivotRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PivotRequest pivotRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pivotRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PivotRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pivotRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PivotRequest pivotRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pivotRequest.Indicator == null)
                throw new ArgumentNullException(nameof(pivotRequest.Indicator), "Property is required for class PivotRequest.");

            if (pivotRequest.IndicatorType == null)
                throw new ArgumentNullException(nameof(pivotRequest.IndicatorType), "Property is required for class PivotRequest.");

            if (pivotRequest.StrategiesOption.IsSet && pivotRequest.Strategies == null)
                throw new ArgumentNullException(nameof(pivotRequest.Strategies), "Property is required for class PivotRequest.");

            writer.WriteString("indicator", pivotRequest.Indicator);

            writer.WriteString("indicatorType", pivotRequest.IndicatorType);

            if (pivotRequest.DepthOption.IsSet)
                writer.WriteNumber("depth", pivotRequest.DepthOption.Value.Value);

            if (pivotRequest.StrategiesOption.IsSet)
            {
                writer.WritePropertyName("strategies");
                JsonSerializer.Serialize(writer, pivotRequest.Strategies, jsonSerializerOptions);
            }
            if (pivotRequest.MaxNodesOption.IsSet)
                writer.WriteNumber("maxNodes", pivotRequest.MaxNodesOption.Value.Value);
        }
    }
}
