// <auto-generated>
/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisper.Api.Sdk.Client;

namespace Whisper.Api.Sdk.Model
{
    /// <summary>
    /// Detailed configuration for each domain variation technique
    /// </summary>
    public partial class TechniqueConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TechniqueConfig" /> class.
        /// </summary>
        /// <param name="typosquatting">typosquatting</param>
        /// <param name="homoglyph">homoglyph</param>
        /// <param name="bitsquatting">bitsquatting</param>
        /// <param name="tldVariation">tldVariation</param>
        [JsonConstructor]
        public TechniqueConfig(Option<TyposquattingConfig> typosquatting = default, Option<HomoglyphConfig> homoglyph = default, Option<BitsquattingConfig> bitsquatting = default, Option<TldVariationConfig> tldVariation = default)
        {
            TyposquattingOption = typosquatting;
            HomoglyphOption = homoglyph;
            BitsquattingOption = bitsquatting;
            TldVariationOption = tldVariation;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Typosquatting
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TyposquattingConfig> TyposquattingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Typosquatting
        /// </summary>
        [JsonPropertyName("typosquatting")]
        public TyposquattingConfig Typosquatting { get { return this.TyposquattingOption; } set { this.TyposquattingOption = new(value); } }

        /// <summary>
        /// Used to track the state of Homoglyph
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<HomoglyphConfig> HomoglyphOption { get; private set; }

        /// <summary>
        /// Gets or Sets Homoglyph
        /// </summary>
        [JsonPropertyName("homoglyph")]
        public HomoglyphConfig Homoglyph { get { return this.HomoglyphOption; } set { this.HomoglyphOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bitsquatting
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BitsquattingConfig> BitsquattingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bitsquatting
        /// </summary>
        [JsonPropertyName("bitsquatting")]
        public BitsquattingConfig Bitsquatting { get { return this.BitsquattingOption; } set { this.BitsquattingOption = new(value); } }

        /// <summary>
        /// Used to track the state of TldVariation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TldVariationConfig> TldVariationOption { get; private set; }

        /// <summary>
        /// Gets or Sets TldVariation
        /// </summary>
        [JsonPropertyName("tld_variation")]
        public TldVariationConfig TldVariation { get { return this.TldVariationOption; } set { this.TldVariationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TechniqueConfig {\n");
            sb.Append("  Typosquatting: ").Append(Typosquatting).Append("\n");
            sb.Append("  Homoglyph: ").Append(Homoglyph).Append("\n");
            sb.Append("  Bitsquatting: ").Append(Bitsquatting).Append("\n");
            sb.Append("  TldVariation: ").Append(TldVariation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TechniqueConfig" />
    /// </summary>
    public class TechniqueConfigJsonConverter : JsonConverter<TechniqueConfig>
    {
        /// <summary>
        /// Deserializes json to <see cref="TechniqueConfig" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TechniqueConfig Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<TyposquattingConfig> typosquatting = default;
            Option<HomoglyphConfig> homoglyph = default;
            Option<BitsquattingConfig> bitsquatting = default;
            Option<TldVariationConfig> tldVariation = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "typosquatting":
                            typosquatting = new Option<TyposquattingConfig>(JsonSerializer.Deserialize<TyposquattingConfig>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "homoglyph":
                            homoglyph = new Option<HomoglyphConfig>(JsonSerializer.Deserialize<HomoglyphConfig>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "bitsquatting":
                            bitsquatting = new Option<BitsquattingConfig>(JsonSerializer.Deserialize<BitsquattingConfig>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "tld_variation":
                            tldVariation = new Option<TldVariationConfig>(JsonSerializer.Deserialize<TldVariationConfig>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (typosquatting.IsSet && typosquatting.Value == null)
                throw new ArgumentNullException(nameof(typosquatting), "Property is not nullable for class TechniqueConfig.");

            if (homoglyph.IsSet && homoglyph.Value == null)
                throw new ArgumentNullException(nameof(homoglyph), "Property is not nullable for class TechniqueConfig.");

            if (bitsquatting.IsSet && bitsquatting.Value == null)
                throw new ArgumentNullException(nameof(bitsquatting), "Property is not nullable for class TechniqueConfig.");

            if (tldVariation.IsSet && tldVariation.Value == null)
                throw new ArgumentNullException(nameof(tldVariation), "Property is not nullable for class TechniqueConfig.");

            return new TechniqueConfig(typosquatting, homoglyph, bitsquatting, tldVariation);
        }

        /// <summary>
        /// Serializes a <see cref="TechniqueConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="techniqueConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TechniqueConfig techniqueConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, techniqueConfig, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TechniqueConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="techniqueConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TechniqueConfig techniqueConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            if (techniqueConfig.TyposquattingOption.IsSet && techniqueConfig.Typosquatting == null)
                throw new ArgumentNullException(nameof(techniqueConfig.Typosquatting), "Property is required for class TechniqueConfig.");

            if (techniqueConfig.HomoglyphOption.IsSet && techniqueConfig.Homoglyph == null)
                throw new ArgumentNullException(nameof(techniqueConfig.Homoglyph), "Property is required for class TechniqueConfig.");

            if (techniqueConfig.BitsquattingOption.IsSet && techniqueConfig.Bitsquatting == null)
                throw new ArgumentNullException(nameof(techniqueConfig.Bitsquatting), "Property is required for class TechniqueConfig.");

            if (techniqueConfig.TldVariationOption.IsSet && techniqueConfig.TldVariation == null)
                throw new ArgumentNullException(nameof(techniqueConfig.TldVariation), "Property is required for class TechniqueConfig.");

            if (techniqueConfig.TyposquattingOption.IsSet)
            {
                writer.WritePropertyName("typosquatting");
                JsonSerializer.Serialize(writer, techniqueConfig.Typosquatting, jsonSerializerOptions);
            }
            if (techniqueConfig.HomoglyphOption.IsSet)
            {
                writer.WritePropertyName("homoglyph");
                JsonSerializer.Serialize(writer, techniqueConfig.Homoglyph, jsonSerializerOptions);
            }
            if (techniqueConfig.BitsquattingOption.IsSet)
            {
                writer.WritePropertyName("bitsquatting");
                JsonSerializer.Serialize(writer, techniqueConfig.Bitsquatting, jsonSerializerOptions);
            }
            if (techniqueConfig.TldVariationOption.IsSet)
            {
                writer.WritePropertyName("tld_variation");
                JsonSerializer.Serialize(writer, techniqueConfig.TldVariation, jsonSerializerOptions);
            }
        }
    }
}
