// <auto-generated>
/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Whisper.Api.Sdk.Client;

namespace Whisper.Api.Sdk.Model
{
    /// <summary>
    /// Industry threat landscape
    /// </summary>
    public partial class ThreatProfile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreatProfile" /> class.
        /// </summary>
        /// <param name="topThreats">Top threat types</param>
        /// <param name="commonVectors">Common attack vectors</param>
        /// <param name="attackFrequency">Average attack frequency per month</param>
        /// <param name="targetedAssets">Most targeted assets</param>
        [JsonConstructor]
        public ThreatProfile(Option<List<string>> topThreats = default, Option<List<string>> commonVectors = default, Option<string> attackFrequency = default, Option<List<string>> targetedAssets = default)
        {
            TopThreatsOption = topThreats;
            CommonVectorsOption = commonVectors;
            AttackFrequencyOption = attackFrequency;
            TargetedAssetsOption = targetedAssets;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TopThreats
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> TopThreatsOption { get; private set; }

        /// <summary>
        /// Top threat types
        /// </summary>
        /// <value>Top threat types</value>
        [JsonPropertyName("topThreats")]
        public List<string> TopThreats { get { return this.TopThreatsOption; } set { this.TopThreatsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CommonVectors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> CommonVectorsOption { get; private set; }

        /// <summary>
        /// Common attack vectors
        /// </summary>
        /// <value>Common attack vectors</value>
        [JsonPropertyName("commonVectors")]
        public List<string> CommonVectors { get { return this.CommonVectorsOption; } set { this.CommonVectorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AttackFrequency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AttackFrequencyOption { get; private set; }

        /// <summary>
        /// Average attack frequency per month
        /// </summary>
        /// <value>Average attack frequency per month</value>
        [JsonPropertyName("attackFrequency")]
        public string AttackFrequency { get { return this.AttackFrequencyOption; } set { this.AttackFrequencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetedAssets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> TargetedAssetsOption { get; private set; }

        /// <summary>
        /// Most targeted assets
        /// </summary>
        /// <value>Most targeted assets</value>
        [JsonPropertyName("targetedAssets")]
        public List<string> TargetedAssets { get { return this.TargetedAssetsOption; } set { this.TargetedAssetsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThreatProfile {\n");
            sb.Append("  TopThreats: ").Append(TopThreats).Append("\n");
            sb.Append("  CommonVectors: ").Append(CommonVectors).Append("\n");
            sb.Append("  AttackFrequency: ").Append(AttackFrequency).Append("\n");
            sb.Append("  TargetedAssets: ").Append(TargetedAssets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ThreatProfile" />
    /// </summary>
    public class ThreatProfileJsonConverter : JsonConverter<ThreatProfile>
    {
        /// <summary>
        /// Deserializes json to <see cref="ThreatProfile" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ThreatProfile Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>> topThreats = default;
            Option<List<string>> commonVectors = default;
            Option<string> attackFrequency = default;
            Option<List<string>> targetedAssets = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "topThreats":
                            topThreats = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "commonVectors":
                            commonVectors = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "attackFrequency":
                            attackFrequency = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "targetedAssets":
                            targetedAssets = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (topThreats.IsSet && topThreats.Value == null)
                throw new ArgumentNullException(nameof(topThreats), "Property is not nullable for class ThreatProfile.");

            if (commonVectors.IsSet && commonVectors.Value == null)
                throw new ArgumentNullException(nameof(commonVectors), "Property is not nullable for class ThreatProfile.");

            if (attackFrequency.IsSet && attackFrequency.Value == null)
                throw new ArgumentNullException(nameof(attackFrequency), "Property is not nullable for class ThreatProfile.");

            if (targetedAssets.IsSet && targetedAssets.Value == null)
                throw new ArgumentNullException(nameof(targetedAssets), "Property is not nullable for class ThreatProfile.");

            return new ThreatProfile(topThreats, commonVectors, attackFrequency, targetedAssets);
        }

        /// <summary>
        /// Serializes a <see cref="ThreatProfile" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="threatProfile"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ThreatProfile threatProfile, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, threatProfile, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ThreatProfile" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="threatProfile"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ThreatProfile threatProfile, JsonSerializerOptions jsonSerializerOptions)
        {
            if (threatProfile.TopThreatsOption.IsSet && threatProfile.TopThreats == null)
                throw new ArgumentNullException(nameof(threatProfile.TopThreats), "Property is required for class ThreatProfile.");

            if (threatProfile.CommonVectorsOption.IsSet && threatProfile.CommonVectors == null)
                throw new ArgumentNullException(nameof(threatProfile.CommonVectors), "Property is required for class ThreatProfile.");

            if (threatProfile.AttackFrequencyOption.IsSet && threatProfile.AttackFrequency == null)
                throw new ArgumentNullException(nameof(threatProfile.AttackFrequency), "Property is required for class ThreatProfile.");

            if (threatProfile.TargetedAssetsOption.IsSet && threatProfile.TargetedAssets == null)
                throw new ArgumentNullException(nameof(threatProfile.TargetedAssets), "Property is required for class ThreatProfile.");

            if (threatProfile.TopThreatsOption.IsSet)
            {
                writer.WritePropertyName("topThreats");
                JsonSerializer.Serialize(writer, threatProfile.TopThreats, jsonSerializerOptions);
            }
            if (threatProfile.CommonVectorsOption.IsSet)
            {
                writer.WritePropertyName("commonVectors");
                JsonSerializer.Serialize(writer, threatProfile.CommonVectors, jsonSerializerOptions);
            }
            if (threatProfile.AttackFrequencyOption.IsSet)
                writer.WriteString("attackFrequency", threatProfile.AttackFrequency);

            if (threatProfile.TargetedAssetsOption.IsSet)
            {
                writer.WritePropertyName("targetedAssets");
                JsonSerializer.Serialize(writer, threatProfile.TargetedAssets, jsonSerializerOptions);
            }
        }
    }
}
